### PR TITLE
Fix hardcoded password does not work with postgreSQL issue

### PR DESCRIPTION
**Pull request by mStack5522**

### CODE REVIEW

**Comment by mStack5522** [comment]
Please review the changes, thanks!

**Comment by arpost** [comment]
Looks good except for the logging. This module uses slf4j not java.util.logging. See https://github.com/eurekaclinical/cas/blob/65dde3ef70f999aea8efcc3ba877b8c270566008/src/main/java/edu/emory/cci/aiw/cvrg/eureka/cas/AbstractProperties.java for an example.

**Comment by mStack5522** [comment]
Please review it, thanks!

**Comment by arpost** [comment]
Please change the calls to ex.getMessage() to ex. We want the logger to record the entire stack trace. Thx.

**Comment by arpost** [comment]
FYI the example in AbstractProperties that uses ex.getMessage() uses that second argument for variable substitution. You can see the {} in the string. It inserts the exception's message where the curly braces are.

**Comment by mStack5522** [comment]
Thanks for the suggestion! Please review the code.

**Comment by arpost** [comment]
Thanks, merging.

**Pull request merged**
